---
development:
  cloud_name: drinkboard
  api_key: '524481758822216'
  api_secret: BF2QigcKBvYJ8DCucCPqUsVcWvI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: drinkboard
  api_key: '524481758822216'
  api_secret: BF2QigcKBvYJ8DCucCPqUsVcWvI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: drinkboard
  api_key: '524481758822216'
  api_secret: BF2QigcKBvYJ8DCucCPqUsVcWvI
  enhance_image_tag: true
  static_image_support: false
